app_accounts/urls.py
from django.urls import path
from app_accounts.views import *
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = (
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('profile/<int:pk>/update/', login_required(UserUpdateView.as_view()), name='update'),
)

app_landing/urls.py
from django.urls import path
from app_landing.views import *

app_name = 'landing'

urlpatterns = (
    path('', LandingView.as_view(), name='index'),
)

app_project/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from app_project.views import *

app_name = 'app_project'

urlpatterns = (
    path('list/', ProjectListView.as_view(), name='list'),
    path('project_add/', login_required(ProjectCreateView.as_view()), name='create'),
    path('project_update/<str:slug>/', login_required(ProjectUpdateView.as_view()), name='update'),
    path('detail/<str:slug>/', ProjectDetailView.as_view(), name='detail'),
    path('create_payment/<int:pk>/<int:pk_r>/', login_required(create_payment), name='create_payment'),
    path('create_news/<int:pk>/', login_required(create_news), name='create_news'),
)

app_region/urls.py
from django.urls import path
from app_region.views import *

app_name = 'region'

urlpatterns = (
    path('get_city/', get_city, name='get_city'),
    path('project_coord/', project_coord, name='project_coord'),
)

crowfounding/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.conf.urls.static import static
from crowfounding import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app_accounts.urls')),
    path('', include('app_landing.urls')),
    path('app_project/', include('app_project.urls')),
    path('comments/', include('app_comments.urls')),
    path('region/', include('app_region.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico/', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'favicon.ico'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

templates/index.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>crowdfunding</title>
    {% block head %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" href="{% static 'index.css' %}">
        <link rel="stylesheet" href="{% static 'card.css' %}">
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>


    <script src="https://yandex.st/jquery/2.2.3/jquery.min.js" type="text/javascript"></script>

</head>
<body>
{% block navbar %}
    <ul id="dropdown1" class="dropdown-content">
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'accounts:detail' pk=request.user.pk %}">Профиль</a></li>
            <li><a href="{% url 'accounts:logout' %}">Выход</a></li>
        {% endif %}
    </ul>
    <nav class="light-green accent-4">
        <div class="nav-wrapper">
            <a href="{% url 'landing:index' %}" class="brand-logo center">crowdfunding</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="{% url 'app_project:list' %}">Все проекты</a></li>
            </ul>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'app_project:create' %}">Создать проект</a></li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a class="dropdown-trigger" data-target="dropdown1">
                            {{ request.user.get_full_name }}
                            <i class="material-icons right">arrow_drop_down</i>
                        </a>
                    </li>
                {% else %}
                    <li><a href="{% url 'accounts:user_login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <ul class="sidenav" id="mobile-demo">
        {% if request.user.is_authenticated %}
            <li>
                <div class="user-view">
                    <a href="{% url 'accounts:detail' pk=request.user.pk %}">
                        <div class="background">
                            <img src="{% static 'sidenav_background.webp' %}" alt="sidenav_background">
                        </div>
                        {% if request.user.image %}
                            <img class="circle" src="{{ request.user.image.url }}" alt="user_profile_image">
                        {% else %}
                            <img class="circle" src="{% static 'media/user_default_image.png' %}"
                                 alt="user_profile_image">
                        {% endif %}
                        <span class="white-text name">{{ request.user.get_full_name }}</span>
                        <span class="white-text email">{{ request.user.email }}</span>
                    </a>
                </div>
            </li>
        {% else %}
            <li>
                <div class="user-view">
                    <div class="background">
                        <img src="{% static 'sidenav_background.webp' %}" alt="sidenav_background">
                    </div>
                    <span class="white-text name">Гость</span>
                </div>
            </li>
        {% endif %}
        <li><a href="{% url 'app_project:list' %}">Все проекты</a></li>
        <li><a href="{% url 'app_project:create' %}">Создать проект</a></li>
        <li>
            <div class="divider"></div>
        </li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'accounts:logout' %}">Выход</a></li>
        {% else %}
            <li><a href="{% url 'accounts:user_login' %}">Вход</a></li>
        {% endif %}
    </ul>
{% endblock %}
<main>
    {% block content %}
        {% if projects_carusel %}
        <div class="slider">
            <ul class="slides">
                {% for project in projects_carusel %}
                    <li>
                        <a href="{% url 'app_project:detail' slug=project.slug %}">
                            <img alt="" src="{{ project.image.url }}">
                            <div class="caption center-align">
                                <p class="slider-text">{{ project.title }}</p>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <div class="container">
            <div class="section">
                <div class="row">
                    <div class="col s12 m4 l12">
                        <br>
                        <h4>Что такое краудфандинг?</h4>
                        <p>
                            Краудфандинг (от англ. crowdfunding) — это способ коллективного финансирования проектов, при
                            котором
                            деньги на создание нового продукта поступают от его конечных потребителей.
                        </p>
                        <img class="responsive-img" src="../static/crowd_index.jpg">
                        <blockquote>
                            Автор крауд-проекта может собрать средства на реализацию идеи и заранее оценить ее
                            востребованность,
                            а
                            спонсор — сделать вклад в начинание автора и получить за это вознаграждение..
                        </blockquote>
                        <br>
                        <h3>Последние проекты: </h3>
                        <br>
                    </div>
                    <div class="col s12 m4 l6">

                    </div>
                </div>
                <div class="row">
                    {% for p_last in projects_last %}
                        <div class="col s12 m4 l4">
                            <div class="card">
                                <a href="{% url 'app_project:detail' slug=p_last.slug %}">
                                    <div class="media media--2-3">
                                        <div class="primary-title">
                                            <div class="optional-header">
                                                <div class="thumbnail thumbnail--40x40">
                                                    {% if p_last.image %}
                                                        <img src="{{ p_last.author.image.url }}" alt=""
                                                             width="40" height="40">
                                                    {% else %}
                                                        <img class="circle"
                                                             src="{% static 'media/user_default_image.png' %}"
                                                             alt="user_profile_image">
                                                    {% endif %}

                                                </div>
                                                <div class="primary-title">
                                                    <div class="title">{{ p_last.author.get_full_name }}</div>
                                                    <div class="subhead">Автор</div>
                                                </div>
                                            </div>
                                            <div class="primary-text">{{ p_last.title }}</div>
                                            <div class="secondary-text">{{ p_last.category }}</div>
                                        </div>
                                        <img src="{{ p_last.image.url }}"
                                             alt=""
                                             width="960" height="640"></div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <a class="waves-effect waves-light btn green accent-4 right"
                       href="{% url 'app_project:list' %}">Все
                        проекты</a>
                </div>
                <div id="map"></div>
            </div>
        </div>

    {% endblock %}
</main>
{% block footer %}
    <footer class="page-footer light-green accent-4">
        <div class="container">
            <div class="row">
                <div class="col s12 l6">
                    <h5 class="white-text">crowdfounding</h5>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Дипломный проект
            </div>
        </div>
    </footer>
{% endblock %}
{% block scripts %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'yamap.js' %}"></script>
    <script type="text/javascript" src="{% static "jquery.formset.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript" src="{% static 'index.js' %}"></script>
{% endblock %}
</body>
</html>