app_accounts/urls.py
from django.urls import path
from app_accounts.views import *
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = (
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('profile/<int:pk>/update/', login_required(UserUpdateView.as_view()), name='update'),
)

app_project/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from app_project.views import *

app_name = 'app_project'

urlpatterns = (
    path('list/', ProjectListView.as_view(), name='list'),
    path('project_add/', login_required(ProjectCreateView.as_view()), name='create'),
    path('project_update/<str:slug>/', login_required(ProjectUpdateView.as_view()), name='update'),
    path('detail/<str:slug>/', ProjectDetailView.as_view(), name='detail'),
    path('create_payment/<int:pk>/<int:pk_r>/', login_required(create_payment), name='create_payment'),
    path('create_news/<int:pk>/', login_required(create_news), name='create_news'),
)

app_region/urls.py
from django.urls import path
from app_region.views import *

app_name = 'region'

urlpatterns = (
    path('get_city/', get_city, name='get_city'),
    path('project_coord/', project_coord, name='project_coord'),
)

crowfounding/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.conf.urls.static import static
from crowfounding import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app_accounts.urls')),
    path('', include('app_landing.urls')),
    path('app_project/', include('app_project.urls')),
    path('comments/', include('app_comments.urls')),
    path('region/', include('app_region.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico/', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'favicon.ico'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

app_accounts/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.conf import settings
from django.core.validators import EmailValidator
from djchoices import DjangoChoices, ChoiceItem
from phonenumber_field.modelfields import PhoneNumberField

from app_region.models import Region, City
from crowfounding.validators import VkValidator, FacebookValidator, YoutubeValidator, TwitterValidator, OkValidator, \
    InstagramValidator


class SocialLinksMixin(models.Model):
    vk = models.CharField('Вконтакте', max_length=255, null=True, blank=True,
                          validators=[VkValidator()])
    facebook = models.CharField('Facebook', max_length=255, null=True, blank=True,
                                validators=[FacebookValidator()])
    youtube = models.CharField('Youtube', max_length=255, null=True, blank=True,
                               validators=[YoutubeValidator()])
    twitter = models.CharField('Twitter', max_length=255, null=True, blank=True,
                               validators=[TwitterValidator()])
    ok = models.CharField('Одноклассники', max_length=255, null=True, blank=True,
                          validators=[OkValidator()])
    instagram = models.CharField('Instagram', max_length=255, null=True, blank=True,
                                 validators=[InstagramValidator()])

    class Meta:
        abstract = True


class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("Укажите номер телефона!")
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault('user_type', 1)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_active') is not True:
            raise ValueError('Superuser must have is_active=True')
        return self.create_user(email, password, **extra_fields)


class UserType(DjangoChoices):
    admin = ChoiceItem(1, 'Администратор')
    moderator = ChoiceItem(2, 'Модератор')
    user = ChoiceItem(3, 'Пользователь')
    nko = ChoiceItem(4, 'НКО')
    gos = ChoiceItem(5, 'Государственное учреждение')


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    email = models.EmailField(validators=[EmailValidator], unique=True, verbose_name="Email")
    image = models.ImageField(verbose_name="Аватар", blank=True, null=True, upload_to='user_image')
    first_name = models.CharField(verbose_name="Имя", max_length=64, blank=True, null=True)
    middle_name = models.CharField(verbose_name="Отчество", max_length=64, blank=True, null=True)
    last_name = models.CharField(verbose_name="Фамилия", max_length=64, blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=settings.IS_ACTIVE)
    user_type = models.PositiveSmallIntegerField(verbose_name='Уровень доступа', default=UserType.user,
                                                 choices=UserType.choices, blank=True, null=True)
    region = models.ForeignKey(Region, on_delete=models.PROTECT, verbose_name='Регион', blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name='Город', blank=True, null=True)
    bio = RichTextUploadingField('Краткая биография', blank=True, null=True, default='Заполните биографию')
    phone = PhoneNumberField('Номер телефона', blank=True, null=True)
    name_organization = models.CharField(verbose_name="Название организации", max_length=255, blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        if self.first_name and self.middle_name and self.last_name:
            return '{} {} {}'.format(self.last_name, self.first_name, self.middle_name)
        elif self.first_name and self.last_name:
            return '{} {}'.format(self.last_name, self.first_name)
        elif self.first_name and self.middle_name:
            return '{} {}'.format(self.first_name, self.middle_name)
        else:
            return self.email

app_project/models.py
from django.db import models
from django.db.models import Sum
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from pytils.translit import slugify
from djchoices import ChoiceItem, DjangoChoices
from app_region.models import Region, City
from app_accounts.models import User
from app_category.models import Category
from crowfounding.validators import YoutubeValidator
import datetime


class ProjectManager(models.Manager):
    def published(self):
        return self.filter(status=ProjectStatus.published)


class ProjectStatus(DjangoChoices):
    published = ChoiceItem('published', 'Опубликован')
    pending = ChoiceItem('pending', 'На рассмотрении')
    unpublished = ChoiceItem('unpublished', 'Отклонен')


class ProjectState(DjangoChoices):
    gathering = ChoiceItem('published', 'Идет сбор')
    finished = ChoiceItem('pending', 'Закончен')


class Project(models.Model):
    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        ordering = ['-published_date']

    author = models.ForeignKey(User, related_name='author', verbose_name='Автор', null=True, on_delete=models.PROTECT)
    title = models.CharField('Наименование', max_length=255)
    description = RichTextUploadingField('Описание')
    image = models.ImageField('Изображение', upload_to='project_image')
    published_date = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата публикации')
    estimated_amount = models.PositiveIntegerField('Планируемая сумма')
    date_end = models.DateField(blank=True, null=True, verbose_name='Дата окончания')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    important = models.BooleanField('Важность', default=False)
    status = models.CharField('Статус публикации', max_length=50, choices=ProjectStatus.choices,
                              default=ProjectStatus.pending)
    pre_title = models.CharField('Подзаголовок', max_length=255)
    state = models.CharField('Статус сбора средств', max_length=50, choices=ProjectState.choices,
                             default=ProjectState.gathering)
    youtube = models.CharField('Ссылка на Youtube видео', max_length=255, validators=[YoutubeValidator()], null=True,
                               blank=True)
    region = models.ForeignKey(Region, on_delete=models.PROTECT, verbose_name='Регион')
    city = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name='Город')
    slug = models.SlugField(allow_unicode=True, unique=True,
                            max_length=255, null=True, blank=True,
                            help_text='Строковый идентификатор сущности. Не может быть числом. '
                                      'После создания в начало будет дописан номер сущности.')
    objects = ProjectManager()

    def __str__(self):
        return self.title

    def count_payment(self):
        """
        Показывает кол. поступлений
        """
        return self.payment_set.all().count()

    def left_days(self):
        """
        Показывает сколько дней осталось
        """
        return int((self.date_end - self.published_date).days)

    def current_payment(self):
        """
        Показывает текущую сумму поступлений
        """
        payments = self.payment_set.aggregate(Sum('sum'))['sum__sum'] or 0
        return int(payments)

    def percent_payment(self):
        """
        Показывает кол. поступлений в процентах
        """
        return int(int(self.current_payment()) * 100 / self.estimated_amount)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.published_date = timezone.now()
        self.date_end = self.published_date + datetime.timedelta(days=30)
        super(Project, self).save(*args, **kwargs)


class Remuneration(models.Model):
    class Meta:
        verbose_name = 'Вознаграждение'
        verbose_name_plural = 'Вознаграждения'
        ordering = ['-price']

    project = models.ForeignKey('Project', null=True, verbose_name='Проект', on_delete=models.CASCADE)
    title = models.CharField('Наименование', max_length=255)
    image = models.ImageField('Изображение', upload_to='remuneration_image')
    description = models.TextField('Описание')
    disable = models.BooleanField('Заблокировать вознаграждение?', default=False)
    price = models.PositiveIntegerField('Cумма')
    holders = models.ManyToManyField(User, blank=True, verbose_name='Владельцы')

    def __str__(self):
        return self.title


class Payment(models.Model):
    class Meta:
        verbose_name = 'Поступление'
        verbose_name_plural = 'Поступления'
        ordering = ['-created']

    project_payment = models.ForeignKey('Project', on_delete=models.PROTECT, verbose_name='Проект')
    author = models.ForeignKey(User, related_name='author_payment', verbose_name='Автор поддержки', null=True,
                               on_delete=models.CASCADE)
    sum = models.DecimalField('Сумма', max_digits=11, decimal_places=2)
    remuneration = models.ForeignKey(Remuneration, on_delete=models.PROTECT, null=True, blank=True,
                                     verbose_name='Вознаграждение')
    created = models.DateField('Дата создания')

    def __str__(self):
        return 'Поступление на сумму %s руб. Дата: %s' % (self.sum, self.created)

    def save(self, *args, **kwargs):
        self.created = timezone.now()
        super(Payment, self).save(*args, **kwargs)


class News(models.Model):
    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-id']

    project = models.ForeignKey('Project', null=True, verbose_name='Проект', on_delete=models.PROTECT)
    author = models.ForeignKey(User, related_name='author_news', verbose_name='Автор', null=True,
                               on_delete=models.PROTECT)
    title = models.CharField('Наименование', max_length=255)
    description = RichTextUploadingField('Описание')
    created = models.DateField('Дата создания')

    def __str__(self):
        return '%s - %s - %s' % (self.title, self.project, self.created)

    def save(self, *args, **kwargs):
        self.created = timezone.now()
        super(News, self).save(*args, **kwargs)

app_accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, UpdateView

from app_accounts.models import User
from app_project.models import Project, Payment, Remuneration
from app_accounts.forms import UserForm


@csrf_exempt
def user_register(request):
    context = {}
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if password and password2 and password == password2:
            user, ucr = User.objects.get_or_create(email=email)
            if ucr:
                user.set_password(password)
                user.first_name = request.POST.get('first_name')
                user.last_name = request.POST.get('last_name')
                user.save()
                user = authenticate(email=email, password=password)
                login(request, user)
                return HttpResponseRedirect(reverse('accounts:update', kwargs={'pk': user.pk}))
            else:
                context.update({'error': 'Аккаунт с таким email уже существует!'})
        else:
            context.update({'error': 'Пароли не совподают!'})
    return render(request, 'app_accounts/login.html', context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('landing:index'))


@csrf_exempt
def user_login(request):
    error = None
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('landing:index'))
            else:
                error = 'Пользователь заблокирован'
        else:
            error = 'Вы ввели неверный e-mail или пароль'
    context = {'error': error}
    return render(request, 'app_accounts/login.html', context)


class UserDetailView(DetailView):
    model = User
    template_name = 'app_accounts/account_detail.html'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context.update({
            'created_projects': Project.objects.filter(author=context['object']),
            'payment_projects': Payment.objects.filter(author=context['object']),
            'remunerations': Remuneration.objects.filter(holders=context['object']),
        })
        return context


class UserUpdateView(UpdateView):
    model = User
    template_name = 'app_accounts/account_update.html'
    form_class = UserForm
    object = None

    def get_object(self, queryset=None):
        self.object = super(UserUpdateView, self).get_object()
        return self.object

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return self.render_to_response(
            self.get_context_data(form=UserForm(instance=self.object))
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = UserForm(self.request.POST, self.request.FILES, instance=self.object)
        if form.is_valid():
            return self.form_valid(form, )
        else:
            print('Проект ', form.errors)
            return self.form_invalid(form, )

    def form_valid(self, form):
        self.object = form.save()
        self.object.save()
        return HttpResponseRedirect(reverse('accounts:detail', args=(self.object.pk,)))

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(form=form)
        )

templates/app_accounts/account_detail.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="section">
            <div class="row">
                <div class="col s12 m12 l12">
                    <p></p>
                </div>
                <div class="col s12 m6 l5">
                    {% if object.image %}
                        <img class="circle" src="{{ object.image.url }}" alt="user_image_profile">
                    {% else %}
                        <img class="circle" src="{% static 'media/user_default_image.png' %}" alt="user_image_profile">
                    {% endif %}
                </div>
                <div class="col s12 m6 l7">
                    <h4>{{ object.get_full_name }}</h4>
                    {% if request.user.id == object.pk %}
                    <a class="black-text" href="{% url 'accounts:update' pk=object.pk %}"><i
                            class="material-icons prefix">mode_edit</i></a>
                    {% endif %}
                </div>
                <div class="col s12 m6 l7">
                    <p class="slider-text">Информация:</p>
                    <ul class="collection">
                        <li class="collection-item">{{ object.email }}</li>
                        <li class="collection-item">{{ object.get_user_type_display }}</li>
                        {% if object.phone %}
                            <li class="collection-item">{{ object.phone|default:'' }}</li>
                        {% endif %}
                        {% if object.region and object.city %}
                            <li class="collection-item">{{ object.region|default:'' }}, {{ object.city|default:'' }}</li>
                        {% endif %}
                        {% if object.name_organization %}
                            <li class="collection-item">{{ object.name_organization|default:'' }}</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col s12 m4 l12">
                    <ul class="tabs tabs-fixed-width tab-demo z-depth-1">
                        <li class="tab col s12 m4 l3"><a class="active" href="#biography">Биография</a></li>
                        <li class="tab col s12 m4 l3"><a href="#created_project">Созданные проекты</a></li>
                        <li class="tab col s12 m4 l3"><a href="#payment_project">Поддержанные проекты</a></li>
                        <li class="tab col s12 m4 l3"><a href="#remuneration">Вознаграждения</a></li>
                    </ul>
                </div>
                <div class="row">
                    <p></p>
                </div>
                <div id="biography" class="col s12 m6 l12">
                    {% if object.bio != None or object.bio != 'Заполните биографию' %}
                        {{ object.bio|safe }}
                    {% else %}
                        {% if request.user.id == object.id %}
                            Опишите себя!
                        {% else %}
                            Пользователь не имеет биографии.
                        {% endif %}
                    {% endif %}
                </div>
                <div id="created_project" class="col s12 m6 l12">
                    {% for project in created_projects %}
                        <div class="col s12 m4 l4">
                            <div class="card"
                                 {% if project.status == 'pending' or project.status == 'unpublished' %}style="opacity: 0.3 !important;"{% endif %}>
                                {% if project.status == 'published' %}
                                    <a href="{% url 'app_project:detail' slug=project.slug %}">
                                {% endif %}
                                <div class="media media--16-9">
                                    <div class="primary-title">
                                        <div class="primary-text">{{ project.title }}</div>
                                        <div class="secondary-text">{{ project.get_status_display }}</div>
                                    </div>
                                    <img src="{{ project.image.url }}" alt="" width="640" height="426">
                                </div>
                                </a>
                            </div>
                        </div>
                    {% empty %}
                        {% if request.user.id == object.id %}
                            Создайте ваш первый проект.
                        {% else %}
                            Пользователь пока не создал ни один проект.
                        {% endif %}
                    {% endfor %}
                </div>
                <div id="payment_project" class="col s12 m6 l12">
                    <div class="col s12  m6 l12">
                        {% for payment in payment_projects %}
                            <ul class="collection">
                                <a href="{% url 'app_project:detail' slug=payment.project_payment.slug %}">
                                    <li class="collection-item avatar">
                                        {% if payment.author.image %}
                                            <img src="{{ payment.author.image.url }}" alt="" class="circle">
                                        {% else %}
                                            <img class="circle" src="{% static 'media/user_default_image.png' %}"
                                                 alt="user_image_profile">
                                        {% endif %}
                                        <span class="title black-text">{{ payment.author.get_full_name }}</span>
                                        <p class="black-text">{{ payment.sum }} руб.</p>
                                        <div class="secondary-content black-text">{{ payment.created }}</div>
                                    </li>
                                </a>
                            </ul>
                        {% empty %}
                            {% if request.user.id == object.id %}
                                Поддержите ваш первый проект.
                            {% else %}
                                Пользователь пока не оказывал поддержку ни одному из проектов.
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div id="remuneration" class="col s12 m6 l12">
                    <div class="col s12  m6 l12">
                        {% for remuneration in remunerations %}
                            <div class="col s12 m4 l4">
                                <div class="card">
                                    <a href="{% url 'app_project:detail' slug=remuneration.project.slug %}">
                                        <div class="media media--16-9">
                                            <div class="primary-title">
                                                <div class="primary-text">{{ remuneration.title }}</div>
                                                <div class="secondary-text">{{ remuneration.price }}</div>
                                            </div>
                                            <img src="{{ remuneration.image.url }}" alt="" width="640" height="426">
                                        </div>
                                    </a>
                                </div>
                            </div>
                        {% empty %}
                            {% if request.user.id == object.id %}
                                У вас пока нет вознаграждений.
                            {% else %}
                                У пользователя пока нет вознаграждений.
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/app_accounts/account_update.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <div class="section">
            <h5>Редактирование профиля: </h5>
            <br>
            <div class="row">
                <form method="POST" enctype="multipart/form-data" class="col s12 m6 l12">
                    <div class="row">
                        <div class="input-field col s12 m6 l4">
                            <i class="material-icons prefix">title</i>
                            {{ form.first_name }}
                            {{ form.errors.first_name }}
                            <label>Имя:</label>
                        </div>
                        <div class="input-field col s12 m6 l4">
                            <i class="material-icons prefix">title</i>
                            {{ form.last_name }}
                            {{ form.errors.last_name }}
                            <label>Фамилия:</label>
                        </div>
                        <div class="input-field col s12 m6 l4">
                            <i class="material-icons prefix">title</i>
                            {{ form.middle_name }}
                            {{ form.errors.middle_name }}
                            <label>Отчество:</label>
                        </div>
                        <div class="file-field input-field col s12 m6 l10">
                            <div class="btn green accent-4">
                                <span>Аватар:</span>
                                {{ form.image }}
                                {{ form.errors.image }}
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text"
                                       placeholder="Загрузите аватар для вашего аккаунта">
                            </div>
                        </div>
                        <div class="input-field col s12 m6 l2">
                            <i class="material-icons prefix">phone</i>
                            {{ form.phone }}
                            {{ form.errors.phone }}
                            <label>Телефон:</label>
                        </div>
                        <div class="input-field col s12 m3 l6">
                            <select name="region" id="region_filter">
                                <option value="" disabled selected>Выберите регион</option>
                                {% for region in form.fields.region.choices %}
                                    <option value="{{ region.id }}"
                                            {% if region.id == region_id %}selected="selected"{% endif %}>{{ region.name }}</option>
                                {% endfor %}
                            </select>
                            <label>Регион</label>
                        {{ form.errors.region }}
                        </div>
                        <div class="input-field col s12 m3 l6">
                            <select name="city" id="city_filter">
                            </select>
                            <label>Город</label>
                            {{ form.errors.city }}
                        </div>
                        <div class="col s12 m6 l12">
                            <fieldset>
                                <legend>Биография</legend>
                                <div class="center col s12 m6 l12">
                                    {{ form.bio|safe }}
                                    {{ form.errors.bio }}
                                </div>
                            </fieldset>
                        </div>
                        <div class="col s12 m6 l12">
                            <p></p>
                        </div>
                        {% csrf_token %}
                        <div class="col s12 m6 l12">
                            <button class="btn waves-effect waves-light col s12 m6 l12 green accent-4" type="submit"
                                    name="action">
                                Сохранить
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}